version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: user-service-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user_service_prod
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - user-service-network
    command: npm start

  postgres:
    image: postgres:14-alpine
    container_name: user-service-postgres-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_service_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - user-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  user-service-network:
    driver: bridge

volumes:
  postgres_data_prod:
    driver: local 